#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : evdev
Version  : 1.2.0
Release  : 4
URL      : https://files.pythonhosted.org/packages/fe/6e/3fa84a43571dec4d00dc26befccc9867b6b3263651531cbc1345f718860f/evdev-1.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/fe/6e/3fa84a43571dec4d00dc26befccc9867b6b3263651531cbc1345f718860f/evdev-1.2.0.tar.gz
Summary  : Bindings to the Linux input handling subsystem
Group    : Development/Tools
License  : BSD-3-Clause
Requires: evdev-license = %{version}-%{release}
Requires: evdev-python = %{version}-%{release}
Requires: evdev-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
*evdev*
-------
This package provides bindings to the generic input event interface in
Linux. The *evdev* interface serves the purpose of passing events
generated in the kernel directly to userspace through character
devices that are typically located in ``/dev/input/``.

%package license
Summary: license components for the evdev package.
Group: Default

%description license
license components for the evdev package.


%package python
Summary: python components for the evdev package.
Group: Default
Requires: evdev-python3 = %{version}-%{release}

%description python
python components for the evdev package.


%package python3
Summary: python3 components for the evdev package.
Group: Default
Requires: python3-core

%description python3
python3 components for the evdev package.


%prep
%setup -q -n evdev-1.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557778507
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/evdev
cp LICENSE %{buildroot}/usr/share/package-licenses/evdev/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/evdev/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
